export const data = [
  {
    specifycard: [
      {
        id: 0,
        number: "000",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/0.png",
        imgorigin: "./img/specifycard/origin/0.jpg",
        description: "",
      },
      {
        id: 1,
        number: "001",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/1.png",
        imgorigin: "./img/specifycard/origin/1.jpg",
        description: "",
      },
      {
        id: 2,
        number: "002",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/2.png",
        imgorigin: "./img/specifycard/origin/2.jpg",
        description: "",
      },
      {
        id: 3,
        number: "003",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/3.png",
        imgorigin: "./img/specifycard/origin/3.jpg",
        description: "",
      },
      {
        id: 4,
        number: "004",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/4.png",
        imgorigin: "./img/specifycard/origin/4.jpg",
        description: "",
      },
      {
        id: 5,
        number: "005",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/5.png",
        imgorigin: "./img/specifycard/origin/5.jpg",
        description: "",
      },
      {
        id: 6,
        number: "006",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/6.png",
        imgorigin: "./img/specifycard/origin/6.jpg",
        description: "",
      },
      {
        id: 7,
        number: "007",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/7.png",
        imgorigin: "./img/specifycard/origin/7.jpg",
        description: "",
      },
      {
        id: 8,
        number: "008",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/8.png",
        imgorigin: "./img/specifycard/origin/8.jpg",
        description: "",
      },
      {
        id: 9,
        number: "009",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/9.png",
        imgorigin: "./img/specifycard/origin/9.jpg",
        description: "",
      },
      {
        id: 10,
        number: "010",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/10.png",
        imgorigin: "./img/specifycard/origin/10.jpg",
        description: "",
      },
      {
        id: 11,
        number: "011",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/11.png",
        imgorigin: "./img/specifycard/origin/11.jpg",
        description: "",
      },
      {
        id: 12,
        number: "012",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/12.png",
        imgorigin: "./img/specifycard/origin/12.jpg",
        description: "",
      },
      {
        id: 13,
        number: "013",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/13.png",
        imgorigin: "./img/specifycard/origin/13.jpg",
        description: "",
      },
      {
        id: 14,
        number: "014",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/14.png",
        imgorigin: "./img/specifycard/origin/14.jpg",
        description: "",
      },
      {
        id: 15,
        number: "015",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/15.png",
        imgorigin: "./img/specifycard/origin/15.jpg",
        description: "",
      },
      {
        id: 16,
        number: "016",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/16.png",
        imgorigin: "./img/specifycard/origin/16.jpg",
        description: "",
      },
      {
        id: 17,
        number: "017",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/17.png",
        imgorigin: "./img/specifycard/origin/17.jpg",
        description: "",
      },
      {
        id: 18,
        number: "018",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/18.png",
        imgorigin: "./img/specifycard/origin/18.jpg",
        description: "",
      },
      {
        id: 19,
        number: "019",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/19.png",
        imgorigin: "./img/specifycard/origin/19.jpg",
        description: "",
      },
      {
        id: 20,
        number: "020",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/20.png",
        imgorigin: "./img/specifycard/origin/20.jpg",
        description: "",
      },
      {
        id: 21,
        number: "021",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/21.png",
        imgorigin: "./img/specifycard/origin/21.jpg",
        description: "",
      },
      {
        id: 22,
        number: "022",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/22.png",
        imgorigin: "./img/specifycard/origin/22.jpg",
        description: "",
      },
      {
        id: 23,
        number: "023",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/23.png",
        imgorigin: "./img/specifycard/origin/23.jpg",
        description: "",
      },
      {
        id: 24,
        number: "024",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/24.png",
        imgorigin: "./img/specifycard/origin/24.jpg",
        description: "",
      },
      {
        id: 25,
        number: "025",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/25.png",
        imgorigin: "./img/specifycard/origin/25.jpg",
        description: "",
      },
      {
        id: 26,
        number: "026",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/26.png",
        imgorigin: "./img/specifycard/origin/26.jpg",
        description: "",
      },
      {
        id: 27,
        number: "027",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/27.png",
        imgorigin: "./img/specifycard/origin/27.jpg",
        description: "",
      },
      {
        id: 28,
        number: "028",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/28.png",
        imgorigin: "./img/specifycard/origin/28.jpg",
        description: "",
      },
      {
        id: 29,
        number: "029",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/29.png",
        imgorigin: "./img/specifycard/origin/29.jpg",
        description: "",
      },
      {
        id: 30,
        number: "030",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/30.png",
        imgorigin: "./img/specifycard/origin/30.jpg",
        description: "",
      },
      {
        id: 31,
        number: "031",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/31.png",
        imgorigin: "./img/specifycard/origin/31.jpg",
        description: "",
      },
      {
        id: 32,
        number: "032",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/32.png",
        imgorigin: "./img/specifycard/origin/32.jpg",
        description: "",
      },
      {
        id: 33,
        number: "033",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/33.png",
        imgorigin: "./img/specifycard/origin/33.jpg",
        description: "",
      },
      {
        id: 34,
        number: "034",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/34.png",
        imgorigin: "./img/specifycard/origin/34.jpg",
        description: "",
      },
      {
        id: 35,
        number: "035",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/35.png",
        imgorigin: "./img/specifycard/origin/35.jpg",
        description: "",
      },
      {
        id: 36,
        number: "036",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/36.png",
        imgorigin: "./img/specifycard/origin/36.jpg",
        description: "",
      },
      {
        id: 37,
        number: "037",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/37.png",
        imgorigin: "./img/specifycard/origin/37.jpg",
        description: "",
      },
      {
        id: 38,
        number: "038",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/38.png",
        imgorigin: "./img/specifycard/origin/38.jpg",
        description: "",
      },
      {
        id: 39,
        number: "039",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/39.png",
        imgorigin: "./img/specifycard/origin/39.jpg",
        description: "",
      },
      {
        id: 40,
        number: "040",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/40.png",
        imgorigin: "./img/specifycard/origin/40.jpg",
        description: "",
      },
      {
        id: 41,
        number: "041",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/41.png",
        imgorigin: "./img/specifycard/origin/41.jpg",
        description: "",
      },
      {
        id: 42,
        number: "042",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/42.png",
        imgorigin: "./img/specifycard/origin/42.jpg",
        description: "",
      },
      {
        id: 43,
        number: "043",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/43.png",
        imgorigin: "./img/specifycard/origin/43.jpg",
        description: "",
      },
      {
        id: 44,
        number: "044",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/44.png",
        imgorigin: "./img/specifycard/origin/44.jpg",
        description: "",
      },
      {
        id: 45,
        number: "045",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/45.png",
        imgorigin: "./img/specifycard/origin/45.jpg",
        description: "",
      },
      {
        id: 46,
        number: "046",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/46.png",
        imgorigin: "./img/specifycard/origin/46.jpg",
        description: "",
      },
      {
        id: 47,
        number: "047",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/47.png",
        imgorigin: "./img/specifycard/origin/47.jpg",
        description: "",
      },
      {
        id: 48,
        number: "048",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/48.png",
        imgorigin: "./img/specifycard/origin/48.jpg",
        description: "",
      },
      {
        id: 49,
        number: "049",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/49.png",
        imgorigin: "./img/specifycard/origin/49.jpg",
        description: "",
      },
      {
        id: 50,
        number: "050",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/50.png",
        imgorigin: "./img/specifycard/origin/50.jpg",
        description: "",
      },
      {
        id: 51,
        number: "051",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/51.png",
        imgorigin: "./img/specifycard/origin/51.jpg",
        description: "",
      },
      {
        id: 52,
        number: "052",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/52.png",
        imgorigin: "./img/specifycard/origin/52.jpg",
        description: "",
      },
      {
        id: 53,
        number: "053",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/53.png",
        imgorigin: "./img/specifycard/origin/53.jpg",
        description: "",
      },
      {
        id: 54,
        number: "054",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/54.png",
        imgorigin: "./img/specifycard/origin/54.jpg",
        description: "",
      },
      {
        id: 55,
        number: "055",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/55.png",
        imgorigin: "./img/specifycard/origin/55.jpg",
        description: "",
      },
      {
        id: 56,
        number: "056",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/56.png",
        imgorigin: "./img/specifycard/origin/56.jpg",
        description: "",
      },
      {
        id: 57,
        number: "057",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/57.png",
        imgorigin: "./img/specifycard/origin/57.jpg",
        description: "",
      },
      {
        id: 58,
        number: "058",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/58.png",
        imgorigin: "./img/specifycard/origin/58.jpg",
        description: "",
      },
      {
        id: 59,
        number: "059",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/59.png",
        imgorigin: "./img/specifycard/origin/59.jpg",
        description: "",
      },
      {
        id: 60,
        number: "060",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/60.png",
        imgorigin: "./img/specifycard/origin/60.jpg",
        description: "",
      },
      {
        id: 61,
        number: "061",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/61.png",
        imgorigin: "./img/specifycard/origin/61.jpg",
        description: "",
      },
      {
        id: 62,
        number: "062",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/62.png",
        imgorigin: "./img/specifycard/origin/62.jpg",
        description: "",
      },
      {
        id: 63,
        number: "063",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/63.png",
        imgorigin: "./img/specifycard/origin/63.jpg",
        description: "",
      },
      {
        id: 64,
        number: "064",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/64.png",
        imgorigin: "./img/specifycard/origin/64.jpg",
        description: "",
      },
      {
        id: 65,
        number: "065",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/65.png",
        imgorigin: "./img/specifycard/origin/65.jpg",
        description: "",
      },
      {
        id: 66,
        number: "066",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/66.png",
        imgorigin: "./img/specifycard/origin/66.jpg",
        description: "",
      },
      {
        id: 67,
        number: "067",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/67.png",
        imgorigin: "./img/specifycard/origin/67.jpg",
        description: "",
      },
      {
        id: 68,
        number: "068",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/68.png",
        imgorigin: "./img/specifycard/origin/68.jpg",
        description: "",
      },
      {
        id: 69,
        number: "069",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/69.png",
        imgorigin: "./img/specifycard/origin/69.jpg",
        description: "",
      },
      {
        id: 70,
        number: "070",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/70.png",
        imgorigin: "./img/specifycard/origin/70.jpg",
        description: "",
      },
      {
        id: 71,
        number: "071",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/71.png",
        imgorigin: "./img/specifycard/origin/71.jpg",
        description: "",
      },
      {
        id: 72,
        number: "072",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/72.png",
        imgorigin: "./img/specifycard/origin/72.jpg",
        description: "",
      },
      {
        id: 73,
        number: "073",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/73.png",
        imgorigin: "./img/specifycard/origin/73.jpg",
        description: "",
      },
      {
        id: 74,
        number: "074",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/74.png",
        imgorigin: "./img/specifycard/origin/74.jpg",
        description: "",
      },
      {
        id: 75,
        number: "075",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/75.png",
        imgorigin: "./img/specifycard/origin/75.jpg",
        description: "",
      },
      {
        id: 76,
        number: "076",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/76.png",
        imgorigin: "./img/specifycard/origin/76.jpg",
        description: "",
      },
      {
        id: 77,
        number: "077",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/77.png",
        imgorigin: "./img/specifycard/origin/77.jpg",
        description: "",
      },
      {
        id: 78,
        number: "078",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/78.png",
        imgorigin: "./img/specifycard/origin/78.jpg",
        description: "",
      },
      {
        id: 79,
        number: "079",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/79.png",
        imgorigin: "./img/specifycard/origin/79.jpg",
        description: "",
      },
      {
        id: 80,
        number: "080",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/80.png",
        imgorigin: "./img/specifycard/origin/80.jpg",
        description: "",
      },
      {
        id: 81,
        number: "081",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/81.png",
        imgorigin: "./img/specifycard/origin/81.jpg",
        description: "",
      },
      {
        id: 82,
        number: "082",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/82.png",
        imgorigin: "./img/specifycard/origin/82.jpg",
        description: "",
      },
      {
        id: 83,
        number: "083",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/83.png",
        imgorigin: "./img/specifycard/origin/83.jpg",
        description: "",
      },
      {
        id: 84,
        number: "084",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/84.png",
        imgorigin: "./img/specifycard/origin/84.jpg",
        description: "",
      },
      {
        id: 85,
        number: "085",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/85.png",
        imgorigin: "./img/specifycard/origin/85.jpg",
        description: "",
      },
      {
        id: 86,
        number: "086",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/86.png",
        imgorigin: "./img/specifycard/origin/86.jpg",
        description: "",
      },
      {
        id: 87,
        number: "087",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/87.png",
        imgorigin: "./img/specifycard/origin/87.jpg",
        description: "",
      },
      {
        id: 88,
        number: "088",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/88.png",
        imgorigin: "./img/specifycard/origin/88.jpg",
        description: "",
      },
      {
        id: 89,
        number: "089",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/89.png",
        imgorigin: "./img/specifycard/origin/89.jpg",
        description: "",
      },
      {
        id: 90,
        number: "090",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/90.png",
        imgorigin: "./img/specifycard/origin/90.jpg",
        description: "",
      },
      {
        id: 91,
        number: "091",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/91.png",
        imgorigin: "./img/specifycard/origin/91.jpg",
        description: "",
      },
      {
        id: 92,
        number: "092",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/92.png",
        imgorigin: "./img/specifycard/origin/92.jpg",
        description: "",
      },
      {
        id: 93,
        number: "093",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/93.png",
        imgorigin: "./img/specifycard/origin/93.jpg",
        description: "",
      },
      {
        id: 94,
        number: "094",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/94.png",
        imgorigin: "./img/specifycard/origin/94.jpg",
        description: "",
      },
      {
        id: 95,
        number: "095",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/95.png",
        imgorigin: "./img/specifycard/origin/95.jpg",
        description: "",
      },
      {
        id: 96,
        number: "096",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/96.png",
        imgorigin: "./img/specifycard/origin/96.jpg",
        description: "",
      },
      {
        id: 97,
        number: "097",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/97.png",
        imgorigin: "./img/specifycard/origin/97.jpg",
        description: "",
      },
      {
        id: 98,
        number: "098",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/98.png",
        imgorigin: "./img/specifycard/origin/98.jpg",
        description: "",
      },
      {
        id: 99,
        number: "099",
        name: "",
        rank: "",
        img: "./img/specifycard/sm/99.png",
        imgorigin: "./img/specifycard/origin/99.jpg",
        description: "",
      },
    ],
  },
  {
    magiccard: [
      {
        id: 1001,
        number: "1001",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/1.png",
        imgorigin: "./img/magiccard/origin/1.png",
        description: "",
      },
      {
        id: 1002,
        number: "1002",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/2.png",
        imgorigin: "./img/magiccard/origin/2.png",
        description: "",
      },
      {
        id: 1003,
        number: "1003",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/3.png",
        imgorigin: "./img/magiccard/origin/3.png",
        description: "",
      },
      {
        id: 1004,
        number: "1004",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/4.png",
        imgorigin: "./img/magiccard/origin/4.png",
        description: "",
      },
      {
        id: 1005,
        number: "1005",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/5.png",
        imgorigin: "./img/magiccard/origin/5.png",
        description: "",
      },
      {
        id: 1006,
        number: "1006",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/6.png",
        imgorigin: "./img/magiccard/origin/6.png",
        description: "",
      },
      {
        id: 1007,
        number: "1007",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/7.png",
        imgorigin: "./img/magiccard/origin/7.png",
        description: "",
      },
      {
        id: 1008,
        number: "1008",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/8.png",
        imgorigin: "./img/magiccard/origin/8.png",
        description: "",
      },
      {
        id: 1009,
        number: "1009",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/9.png",
        imgorigin: "./img/magiccard/origin/9.png",
        description: "",
      },
      {
        id: 1010,
        number: "1010",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/10.png",
        imgorigin: "./img/magiccard/origin/10.png",
        description: "",
      },
      {
        id: 1011,
        number: "1011",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/11.png",
        imgorigin: "./img/magiccard/origin/11.png",
        description: "",
      },
      {
        id: 1012,
        number: "1012",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/12.png",
        imgorigin: "./img/magiccard/origin/12.png",
        description: "",
      },
      {
        id: 1013,
        number: "1013",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/13.png",
        imgorigin: "./img/magiccard/origin/13.png",
        description: "",
      },
      {
        id: 1014,
        number: "1014",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/14.png",
        imgorigin: "./img/magiccard/origin/14.png",
        description: "",
      },
      {
        id: 1015,
        number: "1015",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/15.png",
        imgorigin: "./img/magiccard/origin/15.png",
        description: "",
      },
      {
        id: 1016,
        number: "1016",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/16.png",
        imgorigin: "./img/magiccard/origin/16.png",
        description: "",
      },
      {
        id: 1017,
        number: "1017",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/17.png",
        imgorigin: "./img/magiccard/origin/17.png",
        description: "",
      },
      {
        id: 1018,
        number: "1018",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/18.png",
        imgorigin: "./img/magiccard/origin/18.png",
        description: "",
      },
      {
        id: 1019,
        number: "1019",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/19.png",
        imgorigin: "./img/magiccard/origin/19.png",
        description: "",
      },
      {
        id: 1020,
        number: "1020",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/20.png",
        imgorigin: "./img/magiccard/origin/20.png",
        description: "",
      },
      {
        id: 1021,
        number: "1021",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/21.png",
        imgorigin: "./img/magiccard/origin/21.png",
        description: "",
      },
      {
        id: 1022,
        number: "1022",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/22.png",
        imgorigin: "./img/magiccard/origin/22.png",
        description: "",
      },
      {
        id: 1023,
        number: "1023",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/23.png",
        imgorigin: "./img/magiccard/origin/23.png",
        description: "",
      },
      {
        id: 1024,
        number: "1024",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/24.png",
        imgorigin: "./img/magiccard/origin/24.png",
        description: "",
      },
      {
        id: 1025,
        number: "1025",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/25.png",
        imgorigin: "./img/magiccard/origin/25.png",
        description: "",
      },
      {
        id: 1026,
        number: "1026",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/26.png",
        imgorigin: "./img/magiccard/origin/26.png",
        description: "",
      },
      {
        id: 1027,
        number: "1027",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/27.png",
        imgorigin: "./img/magiccard/origin/27.png",
        description: "",
      },
      {
        id: 1028,
        number: "1028",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/28.png",
        imgorigin: "./img/magiccard/origin/28.png",
        description: "",
      },
      {
        id: 1029,
        number: "1029",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/29.png",
        imgorigin: "./img/magiccard/origin/29.png",
        description: "",
      },
      {
        id: 1030,
        number: "1030",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/30.png",
        imgorigin: "./img/magiccard/origin/30.png",
        description: "",
      },
      {
        id: 1031,
        number: "1031",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/31.png",
        imgorigin: "./img/magiccard/origin/31.png",
        description: "",
      },
      {
        id: 1032,
        number: "1032",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/32.png",
        imgorigin: "./img/magiccard/origin/32.png",
        description: "",
      },
      {
        id: 1033,
        number: "1033",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/33.png",
        imgorigin: "./img/magiccard/origin/33.png",
        description: "",
      },
      {
        id: 1034,
        number: "1034",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/34.png",
        imgorigin: "./img/magiccard/origin/34.png",
        description: "",
      },
      {
        id: 1035,
        number: "1035",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/35.png",
        imgorigin: "./img/magiccard/origin/35.png",
        description: "",
      },
      {
        id: 1036,
        number: "1036",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/36.png",
        imgorigin: "./img/magiccard/origin/36.png",
        description: "",
      },
      {
        id: 1037,
        number: "1037",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/37.png",
        imgorigin: "./img/magiccard/origin/37.png",
        description: "",
      },
      {
        id: 1038,
        number: "1038",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/38.png",
        imgorigin: "./img/magiccard/origin/38.png",
        description: "",
      },
      {
        id: 1039,
        number: "1039",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/39.png",
        imgorigin: "./img/magiccard/origin/39.png",
        description: "",
      },
      {
        id: 1040,
        number: "1040",
        name: "",
        rank: "",
        img: "./img/magiccard/sm/40.png",
        imgorigin: "./img/magiccard/origin/40.png",
        description: "",
      },
    ],
  },
  {
    managercard: [
      {
        id: 100,
        number: "-001",
        name: "",
        rank: "",
        img: "./img/managercard/sm/1.png",
        imgorigin: "./img/managercard/origin/1.jpg",
        description: "",
      },
      {
        id: 200,
        number: "-002",
        name: "",
        rank: "",
        img: "./img/managercard/sm/2.png",
        imgorigin: "./img/managercard/origin/2.jpg",
        description: "",
      },
      {
        id: 300,
        number: "-003",
        name: "",
        rank: "",
        img: "./img/managercard/sm/3.png",
        imgorigin: "./img/managercard/origin/3.jpg",
        description: "",
      },
    ],
  },
];
