export const data = [
  {
    specifycard: [
      {
        id: 0,
        number: "000",
        name: "支配者的祝福",
        rank: "SS",
        img: "./img/specifycard/sm/0.png",
        imgorigin: "./img/specifycard/origin/0.jpg",
        description:
          "問答大賽冠軍將能得到城堡，附帶 1 萬人口的村落。村內的人民會遵從你規定的法律和指令生活。",
      },
      {
        id: 1,
        number: "001",
        name: "一坪的密林",
        rank: "SS",
        img: "./img/specifycard/sm/1.png",
        imgorigin: "./img/specifycard/origin/1.jpg",
        description:
          "巨大森林「山神之庭」的入口。許多僅此才有的特有種，林中的動物都很親近人類。",
      },
      {
        id: 2,
        number: "002",
        name: "一坪的海岸線",
        rank: "SS",
        img: "./img/specifycard/sm/2.png",
        imgorigin: "./img/specifycard/origin/2.jpg",
        description:
          "海底洞窟「海神之家」的入口。每當進入此洞窟時，它會改變外貌，令侵入者迷失。",
      },
      {
        id: 3,
        number: "003",
        name: "湧水之壺",
        rank: "A",
        img: "./img/specifycard/sm/3.png",
        imgorigin: "./img/specifycard/origin/3.jpg",
        description: "不斷湧出清澈泉水之壺。1 天會湧出 1440 公升的水。",
      },
      {
        id: 4,
        number: "004",
        name: "美肌溫泉",
        rank: "A",
        img: "./img/specifycard/sm/4.png",
        imgorigin: "./img/specifycard/origin/4.jpg",
        description:
          "可消除所有肌膚問題的溫泉。1 天泡 30 分鐘，肌膚將變得如嬰兒般光滑。",
      },
      {
        id: 5,
        number: "005",
        name: "神隱之洞",
        rank: "S",
        img: "./img/specifycard/sm/5.png",
        imgorigin: "./img/specifycard/origin/5.jpg",
        description:
          "進入此洞再出來，會移動到某個人跡罕至的場所，但國內限定。無論被傳送到何處，仍可毫不費力地回到洞口。",
      },
      {
        id: 6,
        number: "006",
        name: "產酒之泉",
        rank: "A",
        img: "./img/specifycard/sm/6.png",
        imgorigin: "./img/specifycard/origin/6.jpg",
        description:
          "汲取此泉水放置 1 週後，便會變為酒。雖然酒的種類隨機，但味道絕佳。",
      },
      {
        id: 7,
        number: "007",
        name: "懷胎石",
        rank: "S",
        img: "./img/specifycard/sm/7.png",
        imgorigin: "./img/specifycard/origin/7.jpg",
        description:
          "無論男女，只要將此 3 kg 重的石頭貼身攜帶滿 1 個月，再過 1 週必定懷孕。有男石與女石兩種，想生何種性別就帶哪種石頭。",
      },
      {
        id: 8,
        number: "008",
        name: "不可思議之池",
        rank: "S",
        img: "./img/specifycard/sm/8.png",
        imgorigin: "./img/specifycard/origin/8.jpg",
        description:
          "往池中放 1 條魚，隔天就會增加 1 條。無論棲息在何種水域的魚，都能共存生活。",
      },
      {
        id: 9,
        number: "009",
        name: "豐收之樹",
        rank: "S",
        img: "./img/specifycard/sm/9.png",
        imgorigin: "./img/specifycard/origin/9.jpg",
        description:
          "會結出各種水果的樹。無論怎樣採收，隔天仍會結滿果實。水果的種類與數量是隨機的。",
      },
      {
        id: 10,
        number: "010",
        name: "黃金BURURU",
        rank: "A",
        img: "./img/specifycard/sm/10.png",
        imgorigin: "./img/specifycard/origin/10.jpg",
        description:
          "旅遊情報雜誌。刊載許多可邂逅偏好異性的時間與地點。※ るるぶ RURUBU 為日本知名觀光情報站 ",
      },
      {
        id: 11,
        number: "011",
        name: "黃金天秤",
        rank: "B",
        img: "./img/specifycard/sm/11.png",
        imgorigin: "./img/specifycard/origin/11.jpg",
        description:
          "當遇到「選哪個好呢？」這種迫切需要二選一的時候，天秤會做出對你將來較有用的選擇。",
      },
      {
        id: 12,
        number: "012",
        name: "黃金辭典",
        rank: "S",
        img: "./img/specifycard/sm/12.png",
        imgorigin: "./img/specifycard/origin/12.jpg",
        description:
          "教導對持有者有用的詞彙。打開辭典，找出閃著黃金色光芒的詞彙，並記住其意思的話，隔天必定能派上用場。",
      },
      {
        id: 13,
        number: "013",
        name: "幸福存摺",
        rank: "A",
        img: "./img/specifycard/sm/13.png",
        imgorigin: "./img/specifycard/origin/13.jpg",
        description: "將每天未使用的小小幸福存到此存摺，便可換算成金額提領。",
      },
      {
        id: 14,
        number: "014",
        name: "斷緣之剪",
        rank: "B",
        img: "./img/specifycard/sm/14.png",
        imgorigin: "./img/specifycard/origin/14.jpg",
        description:
          "以此剪刀剪不想遇到的人的照片，便不會再度遇到對方。須注意對該照片中所有人有效 ( 本人除外 )。",
      },
      {
        id: 15,
        number: "015",
        name: "任性魔神",
        rank: "S",
        img: "./img/specifycard/sm/15.png",
        imgorigin: "./img/specifycard/origin/15.jpg",
        description:
          "能實現 3 個願望的魔神。但必須提出 1000 個不同的願望，由魔神自行選擇。(「給我 100 億」「給我 101 億」等灌水的願望是不行的 )",
      },
      {
        id: 16,
        number: "016",
        name: "妖精王的忠告",
        rank: "S",
        img: "./img/specifycard/sm/16.png",
        imgorigin: "./img/specifycard/origin/16.jpg",
        description:
          "溫柔但直接地告訴你不足之處，並給予確實的建議。有時會不請自來，有點煩人。",
      },
      {
        id: 17,
        number: "017",
        name: "大天使的氣息",
        rank: "SS",
        img: "./img/specifycard/sm/17.png",
        imgorigin: "./img/specifycard/origin/17.jpg",
        description: "吹一口氣便能治好瀕死的重傷或不治之症。但只會出現 1 次。",
      },
      {
        id: 18,
        number: "018",
        name: "小惡魔的媚眼",
        rank: "A",
        img: "./img/specifycard/sm/18.png",
        imgorigin: "./img/specifycard/origin/18.jpg",
        description:
          "被拋媚眼者，將體驗到世上無法想像的絕頂快感。小惡魔會拋很多次媚眼，小心中毒。",
      },
      {
        id: 19,
        number: "019",
        name: "遊魂枕",
        rank: "A",
        img: "./img/specifycard/sm/19.png",
        imgorigin: "./img/specifycard/origin/19.jpg",
        description:
          "用此枕睡覺，靈魂將能出竅。但 24 小時內不回身體裡的話，會成為真正的幽靈。",
      },
      {
        id: 20,
        number: "020",
        name: "心度計",
        rank: "B",
        img: "./img/specifycard/sm/20.png",
        imgorigin: "./img/specifycard/origin/20.jpg",
        description:
          "能測量你當下的精神狀態。調到 12 點的話，將恢復平靜的精神狀態。配合 TPO，將能控制自己的心。※ TPO：時間 Time、地點 Place、場合 Occasion ",
      },
      {
        id: 21,
        number: "021",
        name: "髑髏眼鏡",
        rank: "B",
        img: "./img/specifycard/sm/21.png",
        imgorigin: "./img/specifycard/origin/21.jpg",
        description:
          "能透視物體的眼鏡。可透過刻度調整強弱，但無法透視唯一魔法都市的咒語卡包裝袋。",
      },
      {
        id: 22,
        number: "022",
        name: "脫啦A夢",
        rank: "A",
        img: "./img/specifycard/sm/22.png",
        imgorigin: "./img/specifycard/origin/22.jpg",
        description:
          "瀕臨絕種的猛獸。有把東西塞進肚子口袋的習性，放進多種超貴重物品的情況也不少。",
      },
      {
        id: 23,
        number: "023",
        name: "即興書",
        rank: "B",
        img: "./img/specifycard/sm/23.png",
        imgorigin: "./img/specifycard/origin/23.jpg",
        description:
          "每次都能享受不同故事的書。看到一半時，若不夾入附屬的書籤，將會變成完全不同的故事，要注意。",
      },
      {
        id: 24,
        number: "024",
        name: "如果電視",
        rank: "A",
        img: "./img/specifycard/sm/24.png",
        imgorigin: "./img/specifycard/origin/24.jpg",
        description:
          "用附屬的遙控器輸入「如果～」的文章，會將其結果以 1 ~ 30 小時的紀錄片節目播放。也可錄影。",
      },
      {
        id: 25,
        number: "025",
        name: "風險骰子",
        rank: "B",
        img: "./img/specifycard/sm/25.png",
        imgorigin: "./img/specifycard/origin/25.jpg",
        description:
          "20 面體的骰子，1 面是大凶，19 面是大吉。出現大吉的話，會發生非常棒的事；但若出現大凶，會發生足以抵消過去所有大吉的不幸。",
      },
      {
        id: 26,
        number: "026",
        name: "7 個工作小人",
        rank: "A",
        img: "./img/specifycard/sm/26.png",
        imgorigin: "./img/specifycard/origin/26.jpg",
        description:
          "只在主人睡覺的時候，代為工作的小人。但無法達到超出主人能力的要求。",
      },
      {
        id: 27,
        number: "027",
        name: "變臉通行回數券",
        rank: "B",
        img: "./img/specifycard/sm/27.png",
        imgorigin: "./img/specifycard/origin/27.jpg",
        description: "出示此券，便能進入任何場所。內含 1000 張。",
      },
      {
        id: 28,
        number: "028",
        name: "見異思遷遙控器",
        rank: "B",
        img: "./img/specifycard/sm/28.png",
        imgorigin: "./img/specifycard/origin/28.jpg",
        description:
          "可以 10 種強弱等級，操作別人對其他人的 10 種感情。( 無法操作別人對自己的感情 )",
      },
      {
        id: 29,
        number: "029",
        name: "強制預約券",
        rank: "A",
        img: "./img/specifycard/sm/29.png",
        imgorigin: "./img/specifycard/origin/29.jpg",
        description:
          "將商品名稱寫在此券上，無論怎樣的商品都能到手，但對市面上未販售的商品無效。當然，不付錢是不行的。內含 1000 張。",
      },
      {
        id: 30,
        number: "030",
        name: "連結軟墊",
        rank: "B",
        img: "./img/specifycard/sm/30.png",
        imgorigin: "./img/specifycard/origin/30.jpg",
        description:
          "只要讓某人坐上這個軟墊，便能讓他實現 1 次你的要求。無法實現超出該人能力的願望。※ コネクション = connection 連結，クッション = cushion 軟墊 ",
      },
      {
        id: 31,
        number: "031",
        name: "給死者的往返明信片",
        rank: "S",
        img: "./img/specifycard/sm/31.png",
        imgorigin: "./img/specifycard/origin/31.jpg",
        description:
          "在去信明信片上寫上死者的姓名和信息，隔天回信明信片就會顯示回信。一組 1000 張。",
      },
      {
        id: 32,
        number: "032",
        name: "黃鶯糖",
        rank: "B",
        img: "./img/specifycard/sm/32.png",
        imgorigin: "./img/specifycard/origin/32.jpg",
        description:
          "只要舔了這糖，直到下次飲食前，都能自由發出任何聲音。1 組 10 袋，1 袋 50 粒。",
      },
      {
        id: 33,
        number: "033",
        name: "賀爾蒙餅乾",
        rank: "S",
        img: "./img/specifycard/sm/33.png",
        imgorigin: "./img/specifycard/origin/33.jpg",
        description:
          "吃了可以改變性別，期限為 24 小時。1 組 10 盒，1 盒 20 片。",
      },
      {
        id: 34,
        number: "034",
        name: "什麼都行問卷",
        rank: "B",
        img: "./img/specifycard/sm/34.png",
        imgorigin: "./img/specifycard/origin/34.jpg",
        description:
          "在問卷上寫下關於自己的各種問題，交給別人，對方就會誠實回答。可使用多次。",
      },
      {
        id: 35,
        number: "035",
        name: "變色龍貓",
        rank: "S",
        img: "./img/specifycard/sm/35.png",
        imgorigin: "./img/specifycard/origin/35.jpg",
        description:
          "瀕臨絕種的稀有動物。馴養後能變成任何動物，但因體積無法變化，會變成小型象或大倉鼠……",
      },
      {
        id: 36,
        number: "036",
        name: "資源回收房",
        rank: "S",
        img: "./img/specifycard/sm/36.png",
        imgorigin: "./img/specifycard/origin/36.jpg",
        description:
          "將壞掉的東西放進去，24 小時後便會被修復得和新品相同。但時間到之前，絕不可打開房門。",
      },
      {
        id: 37,
        number: "037",
        name: "超一流運動選手的蛋",
        rank: "B",
        img: "./img/specifycard/sm/37.png",
        imgorigin: "./img/specifycard/origin/37.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 38,
        number: "038",
        name: "超一流藝術家的蛋",
        rank: "B",
        img: "./img/specifycard/sm/38.png",
        imgorigin: "./img/specifycard/origin/38.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 39,
        number: "039",
        name: "大政治家的蛋",
        rank: "B",
        img: "./img/specifycard/sm/39.png",
        imgorigin: "./img/specifycard/origin/39.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 40,
        number: "040",
        name: "超一流音樂家的蛋",
        rank: "B",
        img: "./img/specifycard/sm/40.png",
        imgorigin: "./img/specifycard/origin/40.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 41,
        number: "041",
        name: "超一流飛行員的蛋",
        rank: "B",
        img: "./img/specifycard/sm/41.png",
        imgorigin: "./img/specifycard/origin/41.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 42,
        number: "042",
        name: "超一流作家的蛋",
        rank: "B",
        img: "./img/specifycard/sm/42.png",
        imgorigin: "./img/specifycard/origin/42.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 43,
        number: "043",
        name: "大賭徒的蛋",
        rank: "B",
        img: "./img/specifycard/sm/43.png",
        imgorigin: "./img/specifycard/origin/43.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 44,
        number: "044",
        name: "大演員的蛋",
        rank: "B",
        img: "./img/specifycard/sm/44.png",
        imgorigin: "./img/specifycard/origin/44.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 45,
        number: "045",
        name: "大社長的蛋",
        rank: "B",
        img: "./img/specifycard/sm/45.png",
        imgorigin: "./img/specifycard/origin/45.jpg",
        description:
          "每天放在手中加溫許願 3 小時，1 年後～10 年後就會孵化為現實的蛋。加溫時祈望的心意越強烈，就越快孵化。",
      },
      {
        id: 46,
        number: "046",
        name: "金粉少女",
        rank: "A",
        img: "./img/specifycard/sm/46.png",
        imgorigin: "./img/specifycard/origin/46.jpg",
        description:
          "全身會噴出金粉的少女。一天沐浴一次，約可得到 500 公克的金子。非常膽小，足不出戶。",
      },
      {
        id: 47,
        number: "047",
        name: "睡眠少女",
        rank: "A",
        img: "./img/specifycard/sm/47.png",
        imgorigin: "./img/specifycard/origin/47.jpg",
        description: "代替你睡覺的少女。如此你便可不睡，24 小時都能活動。",
      },
      {
        id: 48,
        number: "048",
        name: "香氣少女",
        rank: "A",
        img: "./img/specifycard/sm/48.png",
        imgorigin: "./img/specifycard/origin/48.jpg",
        description:
          "會散發讓你覺得最舒服的香氣。只要在她身邊，就能消除壓力，恢復精神。",
      },
      {
        id: 49,
        number: "049",
        name: "掌上人魚",
        rank: "A",
        img: "./img/specifycard/sm/49.png",
        imgorigin: "./img/specifycard/origin/49.jpg",
        description:
          "如其名，可放在掌上的人魚。住在舒服的地方，心情就會很好。有時會用非常美麗的聲音唱歌。",
      },
      {
        id: 50,
        number: "050",
        name: "掌上恐龍",
        rank: "A",
        img: "./img/specifycard/sm/50.png",
        imgorigin: "./img/specifycard/origin/50.jpg",
        description:
          "如其名，可放在掌上的恐龍。進化飛快，每一代都會配合環境改變外形。",
      },
      {
        id: 51,
        number: "051",
        name: "掌上飛龍",
        rank: "S",
        img: "./img/specifycard/sm/51.png",
        imgorigin: "./img/specifycard/origin/51.jpg",
        description:
          "如其名，可放在掌上的飛龍。很聽飼主的話，若灌注愛情養育，還會變得能說人話。",
      },
      {
        id: 52,
        number: "052",
        name: "真珠蝗蟲",
        rank: "B",
        img: "./img/specifycard/sm/52.png",
        imgorigin: "./img/specifycard/origin/52.jpg",
        description: "腹部抱有真珠的蝗蟲。每過十幾年就會大量出沒 1 次。",
      },
      {
        id: 53,
        number: "053",
        name: "國王白大甲蟲",
        rank: "A",
        img: "./img/specifycard/sm/53.png",
        imgorigin: "./img/specifycard/origin/53.jpg",
        description:
          "傳說中的昆蟲。特殊的費洛蒙可誘使其他昆蟲工作，建築一座大巢穴。只有在傍晚散步時，才會走出巢穴。",
      },
      {
        id: 54,
        number: "054",
        name: "千年鳳蝶",
        rank: "A",
        img: "./img/specifycard/sm/54.png",
        imgorigin: "./img/specifycard/origin/54.jpg",
        description: "傳說的昆蟲。捕到此蝶者，子孫將繁榮數代，此為其名稱由來。",
      },
      {
        id: 55,
        number: "055",
        name: "報復商店",
        rank: "A",
        img: "./img/specifycard/sm/55.png",
        imgorigin: "./img/specifycard/origin/55.jpg",
        description:
          "將平日的怨恨告訴店長，就會幫你向對手施以相當程度的報復。若加價還可加重報復。",
      },
      {
        id: 56,
        number: "056",
        name: "回憶照相館",
        rank: "B",
        img: "./img/specifycard/sm/56.png",
        imgorigin: "./img/specifycard/origin/56.jpg",
        description:
          "說出年、月、日與時間，就能拍出自己當時的姿態。可以連續攝影。",
      },
      {
        id: 57,
        number: "057",
        name: "藏身處不動產",
        rank: "A",
        img: "./img/specifycard/sm/57.png",
        imgorigin: "./img/specifycard/origin/57.jpg",
        description:
          "在喜歡的地方蓋出你專屬的房間，入住條件是其他人都不能進入該房間，也不能談論房間的事。",
      },
      {
        id: 58,
        number: "058",
        name: "秘密錄影帶出租店",
        rank: "A",
        img: "./img/specifycard/sm/58.png",
        imgorigin: "./img/specifycard/origin/58.jpg",
        description:
          "能看見他人秘密的錄影帶出租店。入會條件是不讓他人看出借的錄影帶，也不談論內容。",
      },
      {
        id: 59,
        number: "059",
        name: "速成外語學校",
        rank: "A",
        img: "./img/specifycard/sm/59.png",
        imgorigin: "./img/specifycard/origin/59.jpg",
        description:
          "在此上課的時間，會被算進專用的計時器。只有在按下該計時器的期間，外語才會變得流利。",
      },
      {
        id: 60,
        number: "060",
        name: "失物宅急便",
        rank: "B",
        img: "./img/specifycard/sm/60.png",
        imgorigin: "./img/specifycard/origin/60.jpg",
        description:
          "打專線說明失物內容，隔天就會將失物送到。遺失未滿 1 個月以上將不受理。",
      },
      {
        id: 61,
        number: "061",
        name: "投幣式健檢",
        rank: "A",
        img: "./img/specifycard/sm/61.png",
        imgorigin: "./img/specifycard/origin/61.jpg",
        description:
          "花 500J 便能檢查全身，但結果僅有「有異常」和「無異常」。「有異常」時請去醫院。",
      },
      {
        id: 62,
        number: "062",
        name: "國王俱樂部",
        rank: "B",
        img: "./img/specifycard/sm/62.png",
        imgorigin: "./img/specifycard/origin/62.jpg",
        description:
          "在店內的期間，裡面所有人都會聽你命令。但店內的 1 小時等於店外 1 天。",
      },
      {
        id: 63,
        number: "063",
        name: "虛擬餐廳",
        rank: "B",
        img: "./img/specifycard/sm/63.png",
        imgorigin: "./img/specifycard/origin/63.jpg",
        description:
          "只要提出要求，任何料理都能供應。雖然會有飽足感，但只是覺得有吃過了，實際上並未吃進任何東西。最後會提供營養劑。",
      },
      {
        id: 64,
        number: "064",
        name: "魔女的媚藥",
        rank: "B",
        img: "./img/specifycard/sm/64.png",
        imgorigin: "./img/specifycard/origin/64.jpg",
        description:
          "在接吻時，讓意中人吃下此藥，對方就會成為你的俘虜。1 粒的效力是 1 星期。1 瓶 500 粒。",
      },
      {
        id: 65,
        number: "065",
        name: "魔女的回春藥",
        rank: "S",
        img: "./img/specifycard/sm/65.png",
        imgorigin: "./img/specifycard/origin/65.jpg",
        description:
          "吃 1 粒就會年輕 1 歲。變年輕的只有肉體，知識、記憶會完整保留。若吃超過自己歲數的數量則會死亡，要注意。1 瓶 100 粒。",
      },
      {
        id: 66,
        number: "066",
        name: "魔女的瘦身藥",
        rank: "B",
        img: "./img/specifycard/sm/66.png",
        imgorigin: "./img/specifycard/origin/66.jpg",
        description:
          "吃 1 粒，體重就會減輕 1 公斤。1 瓶 200 粒。若吃超過自己體重的數量則會死亡，要注意。",
      },
      {
        id: 67,
        number: "067",
        name: "長老的增高藥",
        rank: "B",
        img: "./img/specifycard/sm/67.png",
        imgorigin: "./img/specifycard/origin/67.jpg",
        description:
          "吃 1 粒就會長高 1 公分。一瓶 100 粒。建議 20 歲後再服用。",
      },
      {
        id: 68,
        number: "068",
        name: "長老的精力增強藥",
        rank: "A",
        img: "./img/specifycard/sm/68.png",
        imgorigin: "./img/specifycard/origin/68.jpg",
        description:
          "讓某部位變得非常有精神，次數和持久力都無話可說。1 瓶 500 粒。",
      },
      {
        id: 69,
        number: "069",
        name: "長老的生髮藥",
        rank: "B",
        img: "./img/specifycard/sm/69.png",
        imgorigin: "./img/specifycard/origin/69.jpg",
        description:
          "塗到的地方會變得毛髮茂密。塗時若不戴手套，手掌和指尖也會長出毛髮。1 瓶 200 ml ( 以頭計算 10 人份 )。",
      },
      {
        id: 70,
        number: "070",
        name: "瘋狂博士的肌肉增強劑",
        rank: "A",
        img: "./img/specifycard/sm/70.png",
        imgorigin: "./img/specifycard/origin/70.jpg",
        description:
          "喝下去能得到想像中的肌肉。必須每天喝 1 公升，持續喝 1 週。味道難以入口。1 組 7 箱，1 箱 10 瓶，每瓶 1 公升。",
      },
      {
        id: 71,
        number: "071",
        name: "瘋狂博士的費洛蒙劑",
        rank: "A",
        img: "./img/specifycard/sm/71.png",
        imgorigin: "./img/specifycard/origin/71.jpg",
        description:
          "噴在身上，就會非常受異性歡迎。但效果無法控制，可能會引發跟蹤狂大量出現的問題，必須注意。",
      },
      {
        id: 72,
        number: "072",
        name: "瘋狂博士的整形機器",
        rank: "A",
        img: "./img/specifycard/sm/72.png",
        imgorigin: "./img/specifycard/origin/72.jpg",
        description:
          "輸入想要的臉型照片，就能依其整形。雖可以手術多次，但手術有 5% 的機率失敗，機器本身有 1% 的機率故障。",
      },
      {
        id: 73,
        number: "073",
        name: "黑暗翡翠",
        rank: "A",
        img: "./img/specifycard/sm/73.png",
        imgorigin: "./img/specifycard/origin/73.jpg",
        description:
          "受過惡魔加持的寶石。當危機快要降臨到持有者身上時，會將該災厄轉給別人。",
      },
      {
        id: 74,
        number: "074",
        name: "賢者的海藍寶石",
        rank: "A",
        img: "./img/specifycard/sm/74.png",
        imgorigin: "./img/specifycard/origin/74.jpg",
        description: "所有者將能結交數個富有知性，且是一輩子的朋友。",
      },
      {
        id: 75,
        number: "075",
        name: "奇運亞歷山大變色石",
        rank: "A",
        img: "./img/specifycard/sm/75.png",
        imgorigin: "./img/specifycard/origin/75.jpg",
        description:
          "所有者能經歷別人不可能經歷的寶貴體驗。但無法選擇幸或不幸……",
      },
      {
        id: 76,
        number: "076",
        name: "流浪的紅寶石",
        rank: "B",
        img: "./img/specifycard/sm/76.png",
        imgorigin: "./img/specifycard/origin/76.jpg",
        description:
          "持有者會得到巨額財富，代價是無法定居。無法在一個地方停留 1 星期。",
      },
      {
        id: 77,
        number: "077",
        name: "召喚美的綠寶石",
        rank: "S",
        img: "./img/specifycard/sm/77.png",
        imgorigin: "./img/specifycard/origin/77.jpg",
        description:
          "美的追求者會像被吸引般，聚集在持有者周圍。你自己也會變得耀眼動人，充滿魅力到認不出來的程度。",
      },
      {
        id: 78,
        number: "078",
        name: "孤獨的藍寶石",
        rank: "B",
        img: "./img/specifycard/sm/78.png",
        imgorigin: "./img/specifycard/origin/78.jpg",
        description:
          "持有者會得到巨額財富，代價是終生孤獨 1 人。朋友、戀人、家人會馬上離開持有者身邊。",
      },
      {
        id: 79,
        number: "079",
        name: "彩虹鑽石",
        rank: "A",
        img: "./img/specifycard/sm/79.png",
        imgorigin: "./img/specifycard/origin/79.jpg",
        description: "發出 7 色光輝的鑽石。只要拿出它求婚，100% 成功。",
      },
      {
        id: 80,
        number: "080",
        name: "浮遊石",
        rank: "S",
        img: "./img/specifycard/sm/80.png",
        imgorigin: "./img/specifycard/origin/80.jpg",
        description:
          "如其名，浮在空中的石頭。1 克拉可浮起 1 個人類。照不到陽光的話就沒有浮力。",
      },
      {
        id: 81,
        number: "081",
        name: "藍色行星",
        rank: "SS",
        img: "./img/specifycard/sm/81.png",
        imgorigin: "./img/specifycard/origin/81.jpg",
        description:
          "獨一無二，閃著藍光的寶石。在成份構成上，不屬於任何寶石，被認為是來自宇宙的禮物，故名。",
      },
      {
        id: 82,
        number: "082",
        name: "天罰之杖",
        rank: "A",
        img: "./img/specifycard/sm/82.png",
        imgorigin: "./img/specifycard/origin/82.jpg",
        description:
          "邊念著想處罰的對象，邊將此杖指向天空，強烈的災難就會降臨在對方或自己之中，造惡業較多的一方。",
      },
      {
        id: 83,
        number: "083",
        name: "真實之劍",
        rank: "B",
        img: "./img/specifycard/sm/83.png",
        imgorigin: "./img/specifycard/origin/83.jpg",
        description:
          "能一刀砍斷假的東西。也用在審判上，令犯罪者害怕。砍到真貨時，刀刃會粉碎，但插回劍鞘，一天即可復原。",
      },
      {
        id: 84,
        number: "084",
        name: "聖騎士的首飾",
        rank: "D",
        img: "./img/specifycard/sm/84.png",
        imgorigin: "./img/specifycard/origin/84.jpg",
        description:
          "把它掛在身上的玩家，不但可以反彈咒語，還可以解除手上中咒的卡片。",
      },
      {
        id: 85,
        number: "085",
        name: "替身之鎧",
        rank: "S",
        img: "./img/specifycard/sm/85.png",
        imgorigin: "./img/specifycard/origin/85.jpg",
        description:
          "使解除卡片化武器的攻擊完全無效的鎧甲。但耐久度為 1 ~ 100 次隨機，注意可能會突然壞掉。",
      },
      {
        id: 86,
        number: "086",
        name: "挫折之弓",
        rank: "A",
        img: "./img/specifycard/sm/86.png",
        imgorigin: "./img/specifycard/origin/86.jpg",
        description:
          "裝備後可使用「離開」，次數為剩餘的箭量。箭有 10 支，每使用一次「離開」，就會減少 1 支。",
      },
      {
        id: 87,
        number: "087",
        name: "信念之盾",
        rank: "S",
        img: "./img/specifycard/sm/87.png",
        imgorigin: "./img/specifycard/origin/87.jpg",
        description:
          "裝配此盾的玩家半徑 20 公尺內，「左遷」「初心」「飄流」「衝突」等咒語無效。",
      },
      {
        id: 88,
        number: "088",
        name: "不死的大金槌",
        rank: "A",
        img: "./img/specifycard/sm/88.png",
        imgorigin: "./img/specifycard/origin/88.jpg",
        description:
          "被此金槌打到者，會受到隨機的攻擊咒語，無法用防禦咒語防守。但對「監牢」「聖騎士的首飾」的使用者無效。",
      },
      {
        id: 89,
        number: "089",
        name: "稅務長的護手",
        rank: "A",
        img: "./img/specifycard/sm/89.png",
        imgorigin: "./img/specifycard/origin/89.jpg",
        description:
          "裝備後可使用咒語「徵收」，但每念 1 次，就會隨機破壞 1 張玩家指定口袋內的卡片。若指定口袋內沒有卡片，就不能使用「徵收」",
      },
      {
        id: 90,
        number: "090",
        name: "記憶之盔",
        rank: "A",
        img: "./img/specifycard/sm/90.png",
        imgorigin: "./img/specifycard/origin/90.jpg",
        description:
          "戴著它時，看過、聽過的事絕不會忘記。美中不足的是非常笨重。",
      },
      {
        id: 91,
        number: "091",
        name: "模型王",
        rank: "A",
        img: "./img/specifycard/sm/91.png",
        imgorigin: "./img/specifycard/origin/91.jpg",
        description:
          "依組合方式不同，能製作出各種交通工具。當然可用 1 比 1 的規模駕駛，但燃料另售。",
      },
      {
        id: 92,
        number: "092",
        name: "影武者套票",
        rank: "S",
        img: "./img/specifycard/sm/92.png",
        imgorigin: "./img/specifycard/origin/92.jpg",
        description:
          "將票撕下給想要交換的對象，便能交換身分 24 小時。內含 1000 張。",
      },
      {
        id: 93,
        number: "093",
        name: "人生圖鑑",
        rank: "B",
        img: "./img/specifycard/sm/93.png",
        imgorigin: "./img/specifycard/origin/93.jpg",
        description:
          "收錄了出生到現在所有接觸過的人物，記滿了與他們的認識經過與對話等回憶。多達數十萬頁的例子也不稀奇。",
      },
      {
        id: 94,
        number: "094",
        name: "盜賊之劍",
        rank: "S",
        img: "./img/specifycard/sm/94.png",
        imgorigin: "./img/specifycard/origin/94.jpg",
        description:
          "若以此劍成功攻擊，將可隨機給對手「強奪」「扒手」「竊盜」的效果。但對「監牢」「聖騎士的首飾」的使用者無效。",
      },
      {
        id: 95,
        number: "095",
        name: "秘密斗篷",
        rank: "A",
        img: "./img/specifycard/sm/95.png",
        imgorigin: "./img/specifycard/origin/95.jpg",
        description: "披在身上，就能得到持續的「暗幕」效果。",
      },
      {
        id: 96,
        number: "096",
        name: "千里眼之蛇",
        rank: "A",
        img: "./img/specifycard/sm/96.png",
        imgorigin: "./img/specifycard/origin/96.jpg",
        description: "給牠吃 1 張等級 C 以上的卡片，就會吐出「念視」的卡片",
      },
      {
        id: 97,
        number: "097",
        name: "3D 相機",
        rank: "A",
        img: "./img/specifycard/sm/97.png",
        imgorigin: "./img/specifycard/origin/97.jpg",
        description:
          "能將拍攝到的物體以立體方式顯像。不僅能調整大小，質感也能忠實呈現。",
      },
      {
        id: 98,
        number: "098",
        name: "銀狗",
        rank: "S",
        img: "./img/specifycard/sm/98.png",
        imgorigin: "./img/specifycard/origin/98.jpg",
        description:
          "瀕臨絕種的稀有動物。長有銀色的毛，糞便也是銀所構成。1 天將 5 克的金混入狗食給牠吃的話，就會排出 1 公斤的銀糞。",
      },
      {
        id: 99,
        number: "099",
        name: "傭人熊貓",
        rank: "S",
        img: "./img/specifycard/sm/99.png",
        imgorigin: "./img/specifycard/origin/99.jpg",
        description:
          "瀕臨絕種的稀有動物。非常愛乾淨，興趣是做菜，有的還會裁縫和園藝。最重要的是善於照顧人類小孩。",
      },
    ],
  },
  {
    magiccard: [
      {
        id: 1001,
        number: "1001",
        name: "偷窥",
        rank: "G",
        img: "./img/magiccard/sm/1.png",
        imgorigin: "./img/magiccard/origin/1.png",
        description:
          "查看一位目標玩家的所有自由卡槽。（僅限於在遊戲中遇到過的玩家）",
      },
      {
        id: 1002,
        number: "1002",
        name: "透视",
        rank: "F",
        img: "./img/magiccard/sm/2.png",
        imgorigin: "./img/magiccard/origin/2.png",
        description:
          "查看一位目標玩家的所有指定卡槽。（僅限於在遊戲中遇到過的玩家）",
      },
      {
        id: 1003,
        number: "1003",
        name: "防壁",
        rank: "G",
        img: "./img/magiccard/sm/3.png",
        imgorigin: "./img/magiccard/origin/3.png",
        description: "防止一次来自其他玩家的咒語攻擊。",
      },
      {
        id: 1004,
        number: "1004",
        name: "反射",
        rank: "E",
        img: "./img/magiccard/sm/4.png",
        imgorigin: "./img/magiccard/origin/4.png",
        description: "擊退其他玩家的攻擊咒語，並將效果返回给對方。",
      },
      {
        id: 1005,
        number: "1005",
        name: "磁力",
        rank: "C",
        img: "./img/magiccard/sm/5.png",
        imgorigin: "./img/magiccard/origin/5.png",
        description:
          "飛到其他指定玩家（僅限於在遊戲中遇到過的玩家）所在的地点。",
      },
      {
        id: 1006,
        number: "1006",
        name: "扒竊",
        rank: "F",
        img: "./img/magiccard/sm/6.png",
        imgorigin: "./img/magiccard/origin/6.png",
        description: "随機從另一位玩家的自由卡槽那裡竊取一張卡。",
      },
      {
        id: 1007,
        number: "1007",
        name: "盜竊",
        rank: "C",
        img: "./img/magiccard/sm/7.png",
        imgorigin: "./img/magiccard/origin/7.png",
        description: "從另一位玩家的指定卡槽中随機竊取一張卡。",
      },
      {
        id: 1008,
        number: "1008",
        name: "交換",
        rank: "E",
        img: "./img/magiccard/sm/8.png",
        imgorigin: "./img/magiccard/origin/8.png",
        description: "随機用自己的一張卡替換另一張玩家的一張卡。",
      },
      {
        id: 1009,
        number: "1009",
        name: "返回",
        rank: "G",
        img: "./img/magiccard/sm/9.png",
        imgorigin: "./img/magiccard/origin/9.png",
        description: "飛往指定的城市（僅限於去過的城市）。",
      },
      {
        id: 1010,
        number: "1010",
        name: "擬態",
        rank: "A",
        img: "./img/magiccard/sm/10.png",
        imgorigin: "./img/magiccard/origin/10.png",
        description:
          "將您擁有的一張卡轉換為擁有的另一張卡。（變化後的卡片計入這種卡片的卡片化限度枚數。如果卡片化限度枚數為MAX，則變化失敗，並且「擬態」將被銷毁。）",
      },
      {
        id: 1011,
        number: "1011",
        name: "複製",
        rank: "D",
        img: "./img/magiccard/sm/11.png",
        imgorigin: "./img/magiccard/origin/11.png",
        description:
          "從一个目標玩家的指定卡槽卡中随機選擇一張，並將其轉換為該卡。（如果目標玩家指定卡槽中没有卡，或者變化後的卡的卡片化限度枚數為MAX，則變化失敗，並且「復制」將被銷毁。）",
      },
      {
        id: 1012,
        number: "1012",
        name: "降级",
        rank: "F",
        img: "./img/magiccard/sm/12.png",
        imgorigin: "./img/magiccard/origin/12.png",
        description: "令目標玩家飛向島上某处。",
      },
      {
        id: 1013,
        number: "1013",
        name: "初心",
        rank: "D",
        img: "./img/magiccard/sm/13.png",
        imgorigin: "./img/magiccard/origin/13.png",
        description: "令一名目標玩家飛到起点。",
      },
      {
        id: 1014,
        number: "1014",
        name: "退出",
        rank: "B",
        img: "./img/magiccard/sm/14.png",
        imgorigin: "./img/magiccard/origin/14.png",
        description: "令一名目標玩家飛到島外。",
      },
      {
        id: 1015,
        number: "1015",
        name: "念视",
        rank: "D",
        img: "./img/magiccard/sm/15.png",
        imgorigin: "./img/magiccard/origin/15.png",
        description: "查看一位目標玩家的所有卡牌數據。",
      },
      {
        id: 1016,
        number: "1016",
        name: "漂流",
        rank: "F",
        img: "./img/magiccard/sm/16.png",
        imgorigin: "./img/magiccard/origin/16.png",
        description:
          "飛往從未去過的城市。（如果已去過所有城市，您將不會移動並且卡片會被毁。）",
      },
      {
        id: 1017,
        number: "1017",
        name: "冲突",
        rank: "F",
        img: "./img/magiccard/sm/17.png",
        imgorigin: "./img/magiccard/origin/17.png",
        description:
          "飛到一个您從未遇到過的玩家所在的地方。（如果遊戲中没有您從未遇到過的玩家，您將不會移動並且卡片會被毁。）",
      },
      {
        id: 1018,
        number: "1018",
        name: "征收",
        rank: "B",
        img: "./img/magiccard/sm/18.png",
        imgorigin: "./img/magiccard/origin/18.png",
        description:
          "從使用該咒語的玩家周围20m半徑内的所有玩家中随機竊取一張牌。",
      },
      {
        id: 1019,
        number: "1019",
        name: "城門",
        rank: "F",
        img: "./img/magiccard/sm/19.png",
        imgorigin: "./img/magiccard/origin/19.png",
        description: "防止一次其他玩家的近距離攻擊咒語。",
      },
      {
        id: 1020,
        number: "1020",
        name: "贗品",
        rank: "C",
        img: "./img/magiccard/sm/20.png",
        imgorigin: "./img/magiccard/origin/20.png",
        description:
          "將「贗品」更改No.001到099的任何一張卡。可以將轉換後的卡放置在指定卡槽中，但它不滿足集齐卡片的條件，也無法被實體化。不計入卡片化限度枚數。",
      },
      {
        id: 1021,
        number: "1021",
        name: "抢劫",
        rank: "B",
        img: "./img/magiccard/sm/21.png",
        imgorigin: "./img/magiccard/origin/21.png",
        description: "拿走另一位玩家擁有的任何一張卡。",
      },
      {
        id: 1022,
        number: "1022",
        name: "堕落",
        rank: "C",
        img: "./img/magiccard/sm/22.png",
        imgorigin: "./img/magiccard/origin/22.png",
        description:
          "選擇目標玩家的一張B级或更高等级的卡，並將其​​轉換為等级D或更低等级的任意编號的卡。（如果卡片化限度枚數為MAX，或目標玩家没有B级或更高的纸牌，則「堕落」將被銷毁。）變化後，指定卡槽中所有具有不同编號的卡都將被銷毁。",
      },
      {
        id: 1023,
        number: "1023",
        name: "妥協",
        rank: "B",
        img: "./img/magiccard/sm/23.png",
        imgorigin: "./img/magiccard/origin/23.png",
        description:
          "選擇目標玩家的一張A级或更高等级的卡並銷毁它。相反，被銷毁卡的玩家可以指定並得到一張比被銷毁的卡低三级的卡。如果目標玩家没有A级或更高等级的卡，則「妥協」會重新卡片化並退還给玩家。（如果指定的低3级的卡的卡片化限度枚數為MAX，您將不會收到任何卡。）",
      },
      {
        id: 1024,
        number: "1024",
        name: "看破",
        rank: "D",
        img: "./img/magiccard/sm/24.png",
        imgorigin: "./img/magiccard/origin/24.png",
        description:
          "恢復一个目標玩家的卡牌中由「贗品，「復制」和「擬態」變換得的所有卡。由此，指定卡槽中所有具有不同编號的卡都將被銷毁。 「看破」不能成為「贗品」，「復制」或「擬態」的目標。",
      },
      {
        id: 1025,
        number: "1025",
        name: "暗幕",
        rank: "F",
        img: "./img/magiccard/sm/25.png",
        imgorigin: "./img/magiccard/origin/25.png",
        description:
          "使用此卡防止一次其他玩家的「盗竊」和「透视」。（「暗幕」的效果正在持續时，使用另一張「暗幕」並不能使效果生效两次。）",
      },
      {
        id: 1026,
        number: "1026",
        name: "聖水",
        rank: "A",
        img: "./img/magiccard/sm/26.png",
        imgorigin: "./img/magiccard/origin/26.png",
        description:
          "使用此卡的玩家可以防御其他玩家的攻擊咒語10次。（「聖水」的效果正在持續时，使用另一張「聖水」並不會增加防御的次數。）此卡不能被咒語夺取或銷毁。",
      },
      {
        id: 1027,
        number: "1027",
        name: "追踪",
        rank: "E",
        img: "./img/magiccard/sm/27.png",
        imgorigin: "./img/magiccard/origin/27.png",
        description:
          "您總是可以知道一个目標玩家的當前位置。（效果將一直持續到目標玩家退出遊戲為止。）",
      },
      {
        id: 1028,
        number: "1028",
        name: "投石",
        rank: "E",
        img: "./img/magiccard/sm/28.png",
        imgorigin: "./img/magiccard/origin/28.png",
        description:
          "随機選擇並銷毁另一位玩家的一張自由卡槽的卡。（如果目標玩家的自由卡槽中没有卡，則「投石」將被銷毁。）",
      },
      {
        id: 1029,
        number: "1029",
        name: "凶弾",
        rank: "E",
        img: "./img/magiccard/sm/29.png",
        imgorigin: "./img/magiccard/origin/29.png",
        description:
          "從另一位玩家的指定卡槽中随機選擇一張牌並將其銷毁。（如果目標玩家指定卡槽中没有卡，則「凶彈」將被銷毁。）",
      },
      {
        id: 1030,
        number: "1030",
        name: "道標",
        rank: "E",
        img: "./img/magiccard/sm/30.png",
        imgorigin: "./img/magiccard/origin/30.png",
        description: "您可以知道具有指定编號物品的位置。（NO.000除外）",
      },
      {
        id: 1031,
        number: "1031",
        name: "解析",
        rank: "G",
        img: "./img/magiccard/sm/31.png",
        imgorigin: "./img/magiccard/origin/31.png",
        description: "您可以看到指定编號物品卡的描述。（NO.000除外）",
      },
      {
        id: 1032,
        number: "1032",
        name: "宝签",
        rank: "G",
        img: "./img/magiccard/sm/32.png",
        imgorigin: "./img/magiccard/origin/32.png",
        description: "轉換為一張随機物品卡。",
      },
      {
        id: 1033,
        number: "1033",
        name: "附着",
        rank: "C",
        img: "./img/magiccard/sm/33.png",
        imgorigin: "./img/magiccard/origin/33.png",
        description:
          "您始终可以知道一个目標玩家指定卡槽的所有數據。（效果將一直持續到目標玩家退出遊戲為止。）",
      },
      {
        id: 1034,
        number: "1034",
        name: "净化",
        rank: "D",
        img: "./img/magiccard/sm/34.png",
        imgorigin: "./img/magiccard/origin/34.png",
        description:
          "取消攻擊咒語的轉化並恢復原狀。（如果恢復的卡數量為卡片化限度枚數MAX，則將其恢復為物品，此後將無法轉換為卡牌。如果達到卡片化限度枚數MAX的是咒語卡還，則銷毁該卡，除非可以立刻使用該咒語。）",
      },
      {
        id: 1035,
        number: "1035",
        name: "堅牢",
        rank: "S",
        img: "./img/magiccard/sm/35.png",
        imgorigin: "./img/magiccard/origin/35.png",
        description:
          "指定頁面卡槽中的卡片，只要還位於卡槽中，就永远不會被咒語夺取或破坏。（可以指定的頁面限於1到11中的任何一頁，不能選擇自由卡槽頁面。）",
      },
      {
        id: 1036,
        number: "1036",
        name: "神眼",
        rank: "S",
        img: "./img/magiccard/sm/36.png",
        imgorigin: "./img/magiccard/origin/36.png",
        description:
          "使用此卡的玩家可以對於NO.001到099的所有卡獲取「解析」和「名簿」效果。（效果將一直持續到使用它的玩家退出遊戲為止。）",
      },
      {
        id: 1037,
        number: "1037",
        name: "再生",
        rank: "F",
        img: "./img/magiccard/sm/37.png",
        imgorigin: "./img/magiccard/origin/37.png",
        description:
          "解除卡片化得到的物品可以再次轉換為卡牌。（僅限於C级或更低等级的物品。如果目標物品的卡片化限度枚數為MAX，則無法將其重新卡片化，並且「再生」將被破坏。）",
      },
      {
        id: 1038,
        number: "1038",
        name: "名簿",
        rank: "G",
        img: "./img/magiccard/sm/38.png",
        imgorigin: "./img/magiccard/origin/38.png",
        description:
          "您可以指定一種目標物品，並知道當前擁有該物品卡的人數和卡的總數。",
      },
      {
        id: 1039,
        number: "1039",
        name: "同行",
        rank: "F",
        img: "./img/magiccard/sm/39.png",
        imgorigin: "./img/magiccard/origin/39.png",
        description:
          "半徑20m以内的所有玩家（包括使用該咒語的玩家）都飛往指定的城市（僅限於去過的城市）或指定的玩家（僅限於在遊戲中遇到過的玩家）。",
      },
      {
        id: 1040,
        number: "1040",
        name: "通信",
        rank: "F",
        img: "./img/magiccard/sm/40.png",
        imgorigin: "./img/magiccard/origin/40.png",
        description:
          "您可以通過卡片書與其他玩家（僅限於在遊戲中遇到過的玩家）交談。（最長三分鐘，只有使用「通信」的玩家才能在中途斷開通信。）",
      },
    ],
  },
  {
    managercard: [
      {
        id: -1,
        number: "-001",
        name: "掌握",
        rank: "-",
        img: "./img/managercard/sm/1.png",
        imgorigin: "./img/managercard/origin/1.jpg",
        description: "停止 NPC 或敵人的行動。",
      },
      {
        id: -2,
        number: "-002",
        name: "虛無",
        rank: "-",
        img: "./img/managercard/sm/2.png",
        imgorigin: "./img/managercard/origin/2.jpg",
        description: "重製一名玩家的所有卡片數據。",
      },
      {
        id: -3,
        number: "-003",
        name: "排除",
        rank: "-",
        img: "./img/managercard/sm/3.png",
        imgorigin: "./img/managercard/origin/3.jpg",
        description: "所有以非法手段進入貪婪之島的人都會被送往艾珍大陸的某處。",
      },
    ],
  },
  {
    freeslot: [
      {
        id: 100,
        number: "100",
        name: "島的地圖",
        rank: "G",
        img: "./img/freeslot/sm/100.png",
        imgorigin: "./img/freeslot/origin/100.png",
        description:
          "只顯示島的形狀的地圖。內容會籍由實際去過當地，並得到情報後，自動填入的魔法地圖。",
      },
      {
        id: 101,
        number: "101",
        name: "島的地圖",
        rank: "D",
        img: "./img/freeslot/sm/101.png",
        imgorigin: "./img/freeslot/origin/101.png",
        description:
          "詳細記載城市及地名等資料的地圖。有許多特產情報、推薦景點、抄近路地圖等超值情報!",
      },
      {
        id: 102,
        number: "102",
        name: "交換券",
        rank: "SS",
        img: "./img/freeslot/sm/102.png",
        imgorigin: "./img/freeslot/origin/102.png",
        description:
          "可用以交換「大天使的氣息」的券。/「大天使的氣息」的卡片化限度數目為max時才能取得。",
      },
      {
        id: 110,
        number: "110",
        name: "支配者的招待",
        rank: "SS",
        img: "./img/freeslot/sm/110.png",
        imgorigin: "./img/freeslot/origin/110.png",
        description:
          "來自島嶼統治者的邀請。隨附顯示城堡位置的徽章和地圖。只有持有此徽章的人才能進入。",
      },
      {
        id: 163,
        number: "163",
        name: "生病的村民",
        rank: "F",
        img: "./img/freeslot/sm/163.png",
        imgorigin: "./img/freeslot/origin/163.png",
        description: "村民感染島上的流行病",
      },
      {
        id: 263,
        number: "263",
        name: "健康的村民",
        rank: "C",
        img: "./img/freeslot/sm/263.png",
        imgorigin: "./img/freeslot/origin/263.png",
        description: "村民從島上流行病中康復並恢復健康",
      },
      {
        id: 266,
        number: "266",
        name: "通行票",
        rank: "B",
        img: "./img/freeslot/sm/266.png",
        imgorigin: "./img/freeslot/origin/266.png",
        description:
          "離開GI的時候所必要的票卷。用錢向所長買，或是打倒所長即可入手。另外，不管完成多少難題，所長都不會給的。",
      },
      {
        id: 572,
        number: "572",
        name: "獨眼巨人",
        rank: "G",
        img: "./img/freeslot/sm/572.png",
        imgorigin: "./img/freeslot/origin/572.png",
        description:
          "巨人族中身材最巨大的種族。喜歡集體行動，會攻擊侵入地盤的生物。智能低，弱點為眼睛，一旦被打到，就變得出乎意料的脆弱。",
      },
      {
        id: 585,
        number: "585",
        name: "泡泡馬",
        rank: "C",
        img: "./img/freeslot/sm/585.png",
        imgorigin: "./img/freeslot/origin/585.png",
        description:
          "以紅白兩色泡泡迷惑敵人，保護自己。幾乎沒有什麼攻擊力，只是對手會被泡泡的破裂聲嚇到。",
      },
      {
        id: 598,
        number: "598",
        name: "群狼之首",
        rank: "C",
        img: "./img/freeslot/sm/598.png",
        imgorigin: "./img/freeslot/origin/598.png",
        description:
          "成群結隊襲擊旅人的狼的首領。在c等級裏面有著最強的體力以及攻擊力。不打倒首領的話，部下的狼群會無限的出現。",
      },
      {
        id: 607,
        number: "607",
        name: "10000j",
        rank: "H",
        img: "./img/freeslot/sm/607.png",
        imgorigin: "./img/freeslot/origin/607.png",
        description:
          "貪婪之島的最高面額的紙幣。解除卡片化後的形狀和國際通貨紙幣完全一樣。（在貪婪之島中，不是卡片狀態就毫無價值）",
      },
      {
        id: 673,
        number: "673",
        name: "綠球藻",
        rank: "D",
        img: "./img/freeslot/sm/673.png",
        imgorigin: "./img/freeslot/origin/673.png",
        description:
          "以超高速移動的球狀生物。硬度約如橡皮球，被攻擊也不會受傷，只是打到臉上很令人生氣。",
      },
      {
        id: 697,
        number: "697",
        name: "黑色素蜥蜴",
        rank: "E",
        img: "./img/freeslot/sm/697.png",
        imgorigin: "./img/freeslot/origin/697.png",
        description:
          "可吞下整只牛的巨大蜥蜴。背上某處有一敏感的痣，被按一下就會死。為了隱藏弱點，以大小不一的斑點掩飾。",
      },
      {
        id: 711,
        number: "711",
        name: "遙控器老鼠 ",
        rank: "H",
        img: "./img/freeslot/sm/711.png",
        imgorigin: "./img/freeslot/origin/711.png",
        description:
          "用念能力操縱物體自衛的操作系老鼠。非常膽小，只要突然遭到其他生物就會嚇死。繁殖力旺盛，島上隨處可見。",
      },
      {
        id: 1217,
        number: "1217 ",
        name: "加魯加打",
        rank: "F",
        img: "./img/freeslot/sm/1217.png",
        imgorigin: "./img/freeslot/origin/1217.png",
        description:
          "本島三大珍味之一。味道細緻無法憑外表想像。人們相信雌魚的卵具有長壽效果。用煮的或烤的都非常好吃。",
      },
      {
        id: 14170,
        number: "14170",
        name: "汽油",
        rank: "H",
        img: "./img/freeslot/sm/14170.png",
        imgorigin: "./img/freeslot/origin/14170.png",
        description: "玻璃容器中的燃料具有揮發性和易燃性。",
      },
      {
        id: 21449,
        number: "21449",
        name: "石頭",
        rank: "H",
        img: "./img/freeslot/sm/21449.png",
        imgorigin: "./img/freeslot/origin/21449.png",
        description: "路邊平凡無奇的石頭。丟向人可以帶給對方一些傷害。",
      },
      {
        id: 25008,
        number: "25008",
        name: "大石頭",
        rank: "H",
        img: "./img/freeslot/sm/25008.png",
        imgorigin: "./img/freeslot/origin/25008.png",
        description: "一塊大岩石。如果有人被壓在下面，他們將無法毫髮無傷。",
      },
      {
        id: "nan",
        number: "NaN",
        name: "金粉少女護衛",
        rank: "F",
        img: "./img/managercard/sm/nan.png",
        imgorigin: "./img/managercard/origin/nan.png",
        description:
          "金塵少女衛隊穿著西裝，打著領帶。他的頭髮梳理得很整齊，眉毛模糊，下巴裂開。最初，他表現得冷靜而專業，然而，當有人從豪宅中救出金粉女孩時，他變得好戰。",
      },
    ],
  },
];
