export const data = [
  {
    number: "001",
    name: "Beach Glass",
    rank: "a",
    img: "./img/001.png",
    description: "Rank-A",
  },
  {
    number: "002",
    name: "Cactus Fruit",
    rank: "b",
    img: "./img/002.png",
    description: "Rank-B",
  },
  {
    number: "003",
    name: "Chalk Stone",
    rank: "c",
    img: "./img/003.png",
    description: "Rank-C",
  },
  {
    number: "004",
    name: "Flower Fruits",
    rank: "d",
    img: "./img/004.png",
    description: "Rank-D",
  },
  {
    number: "005",
    name: "Lone Earring",
    rank: "e",
    img: "./img/005.png",
    description: "Rank-E",
  },
  {
    number: "006",
    name: "Marble",
    rank: "f",
    img: "./img/006.png",
    description: "Rank-F",
  },
  {
    number: "007",
    name: "Mushroom",
    rank: "g",
    img: "./img/007.png",
    description: "Rank-G",
  },
  {
    number: "008",
    name: "Pinecone",
    rank: "s",
    img: "./img/008.png",
    description: "Rank-S",
  },
  {
    number: "009",
    name: "Torn Ticket",
    rank: "ss",
    img: "./img/009.png",
    description: "Rank-SS",
  },
  {
    number: "010",
    name: "Tropical Flower",
    rank: "a",
    img: "./img/010.png",
    description: "Rank-A",
  },
  {
    number: "011",
    name: "Tropical Shell",
    rank: "b",
    img: "./img/011.png",
    description: "Rank-B",
  },
  {
    number: "012",
    name: "Pretty Leaf",
    rank: "c",
    img: "./img/012.png",
    description: "Rank-C",
  },
  {
    number: "013",
    name: "Skipping Stone",
    rank: "d",
    img: "./img/013.png",
    description: "Rank-D",
  },
  {
    number: "014",
    name: "Small Bouquet",
    rank: "e",
    img: "./img/014.png",
    description: "Rank-E",
  },
  {
    number: "015",
    name: "Stretchy Spring",
    rank: "f",
    img: "./img/015.png",
    description: "Rank-F",
  },
];
